In [1]:
#Web Scraping, getting data from internet

In [2]:
import pandas as pd

In [3]:
df=pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population")[0]

In [4]:
df.head()

,Unnamed: 0,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,–,World,8119000000,100%,1 Jul 2024,UN projection[1][3],NaN
1,1/2 [b],China,1409670000,17.3%,31 Dec 2023,Official estimate[5],[c]
2,1/2 [b],India,1402737000,17.2%,1 Jul 2024,Official projection[6],[d]
3,3,United States,340110988,4.2%,1 Jul 2024,Official estimate[7],[e]
4,4,Indonesia,282477584,3.5%,30 Jun 2024,National annual projection[8],NaN

In [5]:
df.to_excel("datafromint.xlsx")

In [6]:
df=pd.read_clipboard(header=None)

In [7]:
df.head()

                        0
0  http://localhost:8888/

In [8]:
from bs4 import BeautifulSoup
import requests

In [36]:
page=requests.get("http://localhost:8888/")

In [38]:
page.content

b'<!DOCTYPE HTML>\n<html>\n\n<head>\n\n    <meta charset="utf-8">\n\n    <title>Jupyter Server</title>\n    <link id="favicon" rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico?v=50afa725b5de8b00030139d09b38620224d4e7dba47c07ef0e86d4643f30c9bfe6bb7e1a4a1c561aa32834480909a4b6fe7cd1e17f7159330b6b5914bf45a880">\n    \n    <link rel="stylesheet" href="/static/style/bootstrap.min.css?v=0e8a7fbd6de23ad6b27ab95802a0a0915af6693af612bc304d83af445529ce5d95842309ca3405d10f538d45c8a3a261b8cff78b4bd512dd9effb4109a71d0ab" />\n    <link rel="stylesheet" href="/static/style/bootstrap-theme.min.css?v=8b2f045cb5b4d5ad346f6e816aa2566829a4f5f2783ec31d80d46a57de8ac0c3d21fe6e53bcd8e1f38ac17fcd06d12088bc9b43e23b5d1da52d10c6b717b22b3" />\n    <link rel="stylesheet" href="/static/style/index.css?v=30372e3246a801d662cf9e3f9dd656fa192eebde9054a2282449fe43919de9f0ee9b745d7eb49d3b0a5e56357912cc7d776390eddcab9dac85b77bdb17b4bdae" />\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n\n    \n\n\n    \n    \n\n</head>\n\n<body class=""    dir="ltr">\n\n  <noscript>\n    <div id=\'noscript\'>\n      Jupyter Server requires JavaScript.<br>\n      Please enable it to proceed. \n    </div>\n  </noscript>\n\n  <div id="header" role="navigation" aria-label="Top Menu">\n    <div id="header-container" class="container">\n      <div id="jupyter_server" class="nav navbar-brand"><a href="/tree" title=\'dashboard\'>\n          <img src=\'/static/logo/logo.png?v=a2a176ee3cee251ffddf5fa21fe8e43727a9e5f87a06f9c91ad7b776d9e9d3d5e0159c16cc188a3965e00375fb4bc336c16067c688f5040c0c2d4bfdb852a9e4\' alt=\'Jupyter Server\' />\n        </a></div>\n\n      \n      \n\n      \n      \n\n    </div>\n    <div class="header-bar"></div>\n\n    \n    \n  </div>\n\n  <div id="site">\n    \n\n<div id="jupyter-main-app" class="container">\n    \n    \n    <div class="row">\n        <div class="navbar col-sm-8">\n            <div class="navbar-inner">\n                <div class="container">\n                    <div class="center-nav">\n                        <form action="/login?next=%2Ftree" method="post" class="navbar-form pull-left">\n                            <input type="hidden" name="_xsrf" value="2|15c5f207|b5770c43c1b090e5262c874263453af2|1736931127"/>\n                            \n                            <label for="password_input"><strong>Password or token:</strong></label>\n                            \n                            <input type="password" name="password" id="password_input" class="form-control">\n                            <button type="submit" class="btn btn-default" id="login_submit">Log in</button>\n                        </form>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n    \n    \n    \n    \n    <div class="col-sm-6 col-sm-offset-3 text-left rendered_html">\n        <h3>\n            Token authentication is enabled\n        </h3>\n        <p>\n            If no password has been configured, you need to open the\n            server with its login token in the URL, or paste it above.\n            This requirement will be lifted if you\n            <b><a href=\'https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html\'>\n                    enable a password</a></b>.\n        </p>\n        <p>\n            The command:\n        <pre>jupyter server list</pre>\n        will show you the URLs of running servers with their tokens,\n        which you can copy and paste into your browser. For example:\n        </p>\n        <pre>Currently running servers:\nhttp://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks\n</pre>\n        <p>\n            or you can paste just the token value into the password field on this\n            page.\n        </p>\n        <p>\n            See\n            <b><a href=\'https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html\'>\n                    the documentation on how to enable a password</a>\n            </b>\n            in place of token authentication,\n            if you would like to avoid dealing with random tokens.\n        </p>\n        <p>\n            Cookies are required for authenticated access to the Jupyter server.\n        </p>\n        \n        <h3>Setup a Password</h3>\n        <p> You can also setup a password by entering your token and a new password\n            on the fields below:</p>\n        <form action="/login?next=%2Ftree" method="post" class="">\n            <input type="hidden" name="_xsrf" value="2|15c5f207|b5770c43c1b090e5262c874263453af2|1736931127"/>\n            <div class="form-group">\n                <label for="token_input">\n                    <h4>Token</h4>\n                </label>\n                <input type="password" name="password" id="token_input" class="form-control">\n            </div>\n            <div class="form-group">\n                <label for="new_password_input">\n                    <h4>New Password</h4>\n                </label>\n                <input type="password" name="new_password" id="new_password_input" class="form-control" required>\n            </div>\n            <div class="form-group">\n                <button type="submit" class="btn btn-default" id="login_new_pass_submit">Log in and set new\n                    password</button>\n            </div>\n        </form>\n        \n\n    </div>\n    \n    \n</div>\n\n\n  </div>\n\n  \n  \n\n  \n\n\n  <script type=\'text/javascript\'>\n    function _remove_token_from_url() {\n      if (window.location.search.length <= 1) {\n        return;\n      }\n      var search_parameters = window.location.search.slice(1).split(\'&\');\n      for (var i = 0; i < search_parameters.length; i++) {\n        if (search_parameters[i].split(\'=\')[0] === \'token\') {\n          // remote token from search parameters\n          search_parameters.splice(i, 1);\n          var new_search = \'\';\n          if (search_parameters.length) {\n            new_search = \'?\' + search_parameters.join(\'&\');\n          }\n          var new_url = window.location.origin +\n            window.location.pathname +\n            new_search +\n            window.location.hash;\n          window.history.replaceState({}, "", new_url);\n          return;\n        }\n      }\n    }\n    _remove_token_from_url();\n  </script>\n</body>\n\n</html>'

In [40]:
soup=BeautifulSoup(page.content,"html.parser")

In [42]:
soup.prettify

<bound method Tag.prettify of <!DOCTYPE HTML>

<html>
<head>
<meta charset="utf-8"/>
<title>Jupyter Server</title>
<link href="/static/favicon.ico?v=50afa725b5de8b00030139d09b38620224d4e7dba47c07ef0e86d4643f30c9bfe6bb7e1a4a1c561aa32834480909a4b6fe7cd1e17f7159330b6b5914bf45a880" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="/static/style/bootstrap.min.css?v=0e8a7fbd6de23ad6b27ab95802a0a0915af6693af612bc304d83af445529ce5d95842309ca3405d10f538d45c8a3a261b8cff78b4bd512dd9effb4109a71d0ab" rel="stylesheet">
<link href="/static/style/bootstrap-theme.min.css?v=8b2f045cb5b4d5ad346f6e816aa2566829a4f5f2783ec31d80d46a57de8ac0c3d21fe6e53bcd8e1f38ac17fcd06d12088bc9b43e23b5d1da52d10c6b717b22b3" rel="stylesheet"/>
<link href="/static/style/index.css?v=30372e3246a801d662cf9e3f9dd656fa192eebde9054a2282449fe43919de9f0ee9b745d7eb49d3b0a5e56357912cc7d776390eddcab9dac85b77bdb17b4bdae" rel="stylesheet"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
</meta></link></head>
<body class="" dir="ltr">
<noscript>
<div id="noscript">
      Jupyter Server requires JavaScript.<br/>
      Please enable it to proceed.
    </div>
</noscript>
<div aria-label="Top Menu" id="header" role="navigation">
<div class="container" id="header-container">
<div class="nav navbar-brand" id="jupyter_server"><a href="/tree" title="dashboard">
<img alt="Jupyter Server" src="/static/logo/logo.png?v=a2a176ee3cee251ffddf5fa21fe8e43727a9e5f87a06f9c91ad7b776d9e9d3d5e0159c16cc188a3965e00375fb4bc336c16067c688f5040c0c2d4bfdb852a9e4"/>
</a></div>
</div>
<div class="header-bar"></div>
</div>
<div id="site">
<div class="container" id="jupyter-main-app">
<div class="row">
<div class="navbar col-sm-8">
<div class="navbar-inner">
<div class="container">
<div class="center-nav">
<form action="/login?next=%2Ftree" class="navbar-form pull-left" method="post">
<input name="_xsrf" type="hidden" value="2|15c5f207|b5770c43c1b090e5262c874263453af2|1736931127"/>
<label for="password_input"><strong>Password or token:</strong></label>
<input class="form-control" id="password_input" name="password" type="password"/>
<button class="btn btn-default" id="login_submit" type="submit">Log in</button>
</form>
</div>
</div>
</div>
</div>
</div>
<div class="col-sm-6 col-sm-offset-3 text-left rendered_html">
<h3>
            Token authentication is enabled
        </h3>
<p>
            If no password has been configured, you need to open the
            server with its login token in the URL, or paste it above.
            This requirement will be lifted if you
            <b><a href="https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html">
                    enable a password</a></b>.
        </p>
<p>
            The command:
        <pre>jupyter server list</pre>
        will show you the URLs of running servers with their tokens,
        which you can copy and paste into your browser. For example:
        </p>
<pre>Currently running servers:
http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks
</pre>
<p>
            or you can paste just the token value into the password field on this
            page.
        </p>
<p>
            See
            <b><a href="https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html">
                    the documentation on how to enable a password</a>
</b>
            in place of token authentication,
            if you would like to avoid dealing with random tokens.
        </p>
<p>
            Cookies are required for authenticated access to the Jupyter server.
        </p>
<h3>Setup a Password</h3>
<p> You can also setup a password by entering your token and a new password
            on the fields below:</p>
<form action="/login?next=%2Ftree" class="" method="post">
<input name="_xsrf" type="hidden" value="2|15c5f207|b5770c43c1b090e5262c874263453af2|1736931127">
<div class="form-group">
<label for="token_input">
<h4>Token</h4>
</label>
<input class="form-control" id="token_input" name="password" type="password"/>
</div>
<div class="form-group">
<label for="new_password_input">
<h4>New Password</h4>
</label>
<input class="form-control" id="new_password_input" name="new_password" required="" type="password"/>
</div>
<div class="form-group">
<button class="btn btn-default" id="login_new_pass_submit" type="submit">Log in and set new
                    password</button>
</div>
</input></form>
</div>
</div>
</div>
<script type="text/javascript">
    function _remove_token_from_url() {
      if (window.location.search.length <= 1) {
        return;
      }
      var search_parameters = window.location.search.slice(1).split('&');
      for (var i = 0; i < search_parameters.length; i++) {
        if (search_parameters[i].split('=')[0] === 'token') {
          // remote token from search parameters
          search_parameters.splice(i, 1);
          var new_search = '';
          if (search_parameters.length) {
            new_search = '?' + search_parameters.join('&');
          }
          var new_url = window.location.origin +
            window.location.pathname +
            new_search +
            window.location.hash;
          window.history.replaceState({}, "", new_url);
          return;
        }
      }
    }
    _remove_token_from_url();
  </script>
</body>
</html>>

In [46]:
page=requests.get("https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320")

In [48]:
page.content

b'<!doctype html>\r\n\t<html lang="tr">\r\n\t<head>\r\n\t\t<meta charset="utf-8"/>\r\n\t\t<meta http-equiv="X-UA-Compatible" content="IE=edge"/>\r\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1"/>\r\n\t\t<title>Herkes nerede? - Zafer Acar</title>\r\n\t\t<meta name="description" content="Los Alamos Amerika\xe2\x80\x99n\xc4\xb1n New Mexico eyaletinin 2300 metre rak\xc4\xb1ml\xc4\xb1, bir adet s\xc3\xbcpermarketi ve 2 kafesi olan 12 bin n\xc3\xbcfuslu minik bir kasabas\xc4\xb1. Kendisine..." />\n<link rel="canonical" href="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" />\n<link rel="amphtml" href="https://www.karar.com/amp/yazarlar/zafer-acar/herkes-nerede-7320" />\n<meta property="og:type" content="article" />\n<meta property="og:site_name" content="KARAR" />\n<meta property="og:url" content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" />\n<meta property="og:title" content="Herkes nerede? - Zafer Acar" />\n<meta property="og:description" content="Los Alamos Amerika\xe2\x80\x99n\xc4\xb1n New Mexico eyaletinin 2300 metre rak\xc4\xb1ml\xc4\xb1, bir adet s\xc3\xbcpermarketi ve 2 kafesi olan 12 bin n\xc3\xbcfuslu minik bir kasabas\xc4\xb1. Kendisine..." />\n<meta property="og:image" content="https://cdn.karar.com/author/zafer-acar-002.jpg" />\n<meta name="twitter:card" content="summary_large_image" />\n<meta name="twitter:site" content="@KararHaber" />\n<meta name="twitter:url"  content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" />\n<meta name="twitter:title" content="Herkes nerede? - Zafer Acar" />\n<meta name="twitter:description" content="Los Alamos Amerika\xe2\x80\x99n\xc4\xb1n New Mexico eyaletinin 2300 metre rak\xc4\xb1ml\xc4\xb1, bir adet s\xc3\xbcpermarketi ve 2 kafesi olan 12 bin n\xc3\xbcfuslu minik bir kasabas\xc4\xb1. Kendisine..." />\n<meta name="twitter:image" content="https://cdn.karar.com/author/zafer-acar-002.jpg" />\n<meta name="author" content="Zafer Acar" />\n<meta name="title" content="Herkes nerede?" />\n<meta name="url" content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" />\n<meta name="datePublished" content="2018-06-24T23:23:46+03:00" />\n<meta name="articleSection" content="columnist" />\n<meta name="articleAuthor" content="Zafer Acar" />\n<meta name="apple-itunes-app" content="app-id=1009271502" />\n<meta name="google-play-app" content="app-id=com.labdroids.karar" />\n<meta property="fb:app_id" content="668763830688221" />\n\t\t<link rel="alternate" type="application/rss+xml" href="https://www.karar.com/service/rss.php"/>\r\n\t\t<meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1"/>\r\n\t\t<link rel="manifest" href="/manifest.json"/>\r\n\t\t<link rel="icon" href="https://www.karar.com/d/assets/favicon/favicon.ico"/>\r\n\t\t<meta name="generator" content="CM News 6.0"/>\r\n\r\n\t\t<link rel="preconnect" href="https://fonts.gstatic.com"/>\r\n\t\t<link rel="preconnect" href="https://www.google-analytics.com"/>\r\n\t\t<link rel="preconnect" href="https://tpc.googlesyndication.com"/>\r\n\t\t<link rel="preconnect" href="https://pagead2.googlesyndication.com"/>\r\n\r\n\t\t\t\t\t<link rel="preconnect" href="https://fonts.gstatic.com"/>\r\n\t\t\t<link rel="stylesheet" href="https://www.karar.com/d/assets/bundle/karar-desktop-main.css?1727709274"/>\r\n\t\t\t\r\n\t\t<script>\r\n\t\t\tconst BURL = "https://www.karar.com/",\r\n\t\t\t\tDURL = "https://cdn.karar.com/";\r\n\t\t</script>\r\n\r\n\t\t<link rel="apple-touch-icon" sizes="180x180" href="https://cdn.karar.com/assets/favicon/apple-touch-icon.png">\r\n<link rel="mask-icon" href="https://cdn.karar.com/assets/favicon/safari-pinned-tab.svg" color="#e30613">\r\n<meta name="msapplication-TileColor" content="#e30613">\r\n<meta name="theme-color" content="#ffffff">\r\n<meta name=\'Petal-Search-site-verification\' content=\'fd13614ab1\'/>\r\n\r\n<!-- Google tag (gtag.js) -->\r\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-1L3TVQZ3LV"></script>\r\n<script>\r\n  window.dataLayer = window.dataLayer || [];\r\n  function gtag(){dataLayer.push(arguments);}\r\n  gtag(\'js\', new Date());\r\n\r\n  gtag(\'config\', \'G-1L3TVQZ3LV\');\r\n</script>\r\n\r\n<script>!function(){var t=document.createElement("script");t.setAttribute("src",\'https://cdn.p.analitik.bik.gov.tr/tracker\'+(typeof Intl!=="undefined"?(typeof (Intl||"").PluralRules!=="undefined"?\'1\':typeof Promise!=="undefined"?\'2\':typeof MutationObserver!==\'undefined\'?\'3\':\'4\'):\'4\')+\'.js\'),t.setAttribute("data-website-id","d9b8fdca-5069-4cc2-b3f3-6ab32564a106"),t.setAttribute("data-host-url",\'//d9b8fdca-5069-4cc2-b3f3-6ab32564a106.collector.p.analitik.bik.gov.tr\'),document.head.appendChild(t)}();</script>\r\n\r\n\t\t<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977" crossorigin="anonymous"></script>\r\n\r\n<script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>\r\n<script async src="https://adsby.io/headerbidding/adshb.karar.prebid.js"></script>\r\n\r\n\r\n<script>\r\n    window.googletag = window.googletag || { cmd: [] };\r\n    googletag.cmd.push(function () {\r\n        googletag.pubads().disableInitialLoad();\r\n    });\r\n\r\n\tgoogletag.cmd.push(function ()\r\n\t{\r\n\t\tmappingFull = googletag.sizeMapping().\r\n\t\taddSize([1024, 360], [[970, 90], [1000, 250], [970, 250]]).\r\n\t\taddSize([768, 360], [[728, 250], [728, 90]]).\r\n\t\taddSize([360, 360], [[336, 280], [300, 250]]).\r\n\t\taddSize([0, 0], [[320, 100],[300, 100]]).\r\n\t\tbuild();\r\n\r\n\t\tmappingMiddle = googletag.sizeMapping().\r\n\t\taddSize([768, 360], [[670, 250], [640, 300], [336, 280], [300, 250], \'fluid\']).\r\n\t\taddSize([360, 360], [[336, 280], [300, 250]]).\r\n\t\taddSize([0, 0], [300, 250]).\r\n\t\tbuild();\r\n\r\n\t\tmappingSide = googletag.sizeMapping().\r\n\t\taddSize([360, 360], [[336, 280], [300, 250], \'fluid\']).\r\n\t\taddSize([0, 0], [300, 250]).\r\n\t\tbuild();\r\n\r\n\t\tmappingSticky = googletag.sizeMapping().\r\n\t\taddSize([1024, 360], [970, 90]).\r\n\t\taddSize([768, 360], [728, 90]).\r\n\t\taddSize([0, 0], [[300, 100],[320,100]]).\r\n\t\tbuild();\r\n\r\n\t\tmappingPageSkin = googletag.sizeMapping().\r\n\t\taddSize([1720, 600], [[300, 600],[160, 600],[120, 600]]).\r\n\t\taddSize([1520, 600], [[160, 600],[120, 600]]).\r\n\t\taddSize([1440, 600], [[160, 600],[120, 600]]).\r\n\t\taddSize([1366, 600], [[120, 600]]).\r\n\t\taddSize([0, 0], []).\r\n\t\tbuild();\r\n\r\n\t\tmappingMobilM = googletag.sizeMapping().\r\n\t\taddSize([0, 0], [[300, 50], [320, 100], [320, 50], [300, 100]]).\r\n\t\tbuild();\r\n\t\tmappingMobilSC = googletag.sizeMapping().\r\n\t\taddSize([0, 0], [[300,250], [336, 280]]).\r\n\t\tbuild();\r\n    \r\n        \r\n\t\tgoogletag.enableServices();\r\n\t});\r\n</script>\r\n<script src="https://adsby.io/karar/karar.gpt.js?ver=1.15"></script>\r\n<script src="https://adsby.io/theadsiobanner.js?ver=1.15"></script>\r\n\r\n<!--\r\n<script async="async" src="https://cdn.membrana.media/krr/ym.js"></script>\r\n\r\n<script>\r\n\r\n\twindow.yieldMasterCmd = window.yieldMasterCmd || [];\r\n\twindow.yieldMasterCmd.push(function ()\r\n\t{\r\n\t\twindow.yieldMaster.init({\r\n\t\t\tpageVersionAutodetect: true\r\n\t\t});\r\n\t});\r\n\r\n</script>\r\n\r\n-->\r\n\r\n<!--script>\r\n  window.teads_analytics = window.teads_analytics || {};\r\n  window.teads_analytics.analytics_tag_id = "PUB_28922";\r\n  window.teads_analytics.share = window.teads_analytics.share || function() {\r\n    ;(window.teads_analytics.shared_data = window.teads_analytics.shared_data || []).push(arguments)\r\n  };\r\n</script>\r\n<script async src="https://a.teads.tv/analytics/tag.js"></script-->\r\n\r\n<script src="https://jsc.idealmedia.io/site/839414.js" async></script>\r\n\r\n<!-- head end -->\r\n\r\n<style>\r\n    .article-detail .google-auto-placed{\r\n        margin-bottom: 30px;\r\n    }\r\n</style>\t</head>\r\n\t<body class="body-main cat-author author-article-detail author">\r\n\t\t\t\t\t<header class="main-header">\n\t\t<div class="top">\n\t\t\t<div class="container">\n\t\t\t\t<div class="date">15 Ocak 2025 \xc3\x87ar\xc5\x9famba</div>\n\t\t\t\t<div class="currency">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="item up">\n\t\t\t\t\t\t\t<span class="text">Alt\xc4\xb1n</span>\n\t\t\t\t\t\t\t<i class="icon icon-up-dir"></i>\n\t\t\t\t\t\t\t<span class="value">3061.148</span>\n\t\t\t\t\t\t\t<span class="rate">%0.37</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="item down">\n\t\t\t\t\t\t\t<span class="text">BIST</span>\n\t\t\t\t\t\t\t<i class="icon icon-down-dir"></i>\n\t\t\t\t\t\t\t<span class="value">9697.22</span>\n\t\t\t\t\t\t\t<span class="rate">%0,19</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="item up">\n\t\t\t\t\t\t\t<span class="text">Dolar</span>\n\t\t\t\t\t\t\t<i class="icon icon-up-dir"></i>\n\t\t\t\t\t\t\t<span class="value">35.4871</span>\n\t\t\t\t\t\t\t<span class="rate">%0.01</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="item down">\n\t\t\t\t\t\t\t<span class="text">Euro</span>\n\t\t\t\t\t\t\t<i class="icon icon-down-dir"></i>\n\t\t\t\t\t\t\t<span class="value">36.5747</span>\n\t\t\t\t\t\t\t<span class="rate">%0.10</span>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t<div class="social">\n\t\t\t\t\t\t\t\t\t\t\t<a class="youtube" href="https://www.youtube.com/channel/UCoLyFzOzAzNG_-oR-O4relg?sub_confirmation=1" rel="nofollow noopener noreferrer" target="_blank" title="Youtube ile takip et"><i class="icon icon-youtube-play"></i></a>\n\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t<a class="instagram" href="https://www.instagram.com/kararhaber" rel="nofollow noopener noreferrer" target="_blank" title="\xc4\xb0nstagram ile takip et"><i class="icon icon-instagramm"></i></a>\n\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t<a class="facebook" href="https://www.facebook.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Facebook ile takip et"><i class="icon icon-facebook"></i></a>\n\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t<a class="twitter" href="https://twitter.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Twitter ile takip et"><i class="icon icon-twitter"></i></a>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t\t<div class="center">\n\t\t\t<div class="container">\n\t\t\t\t<div class="logo relative">\n\t\t\t\t\t<a href="https://www.karar.com/" rel="home" title="KARAR">\n\t\t\t\t\t\t<img class="lazy" loading="lazy" data-src="https://www.karar.com/d/assets/logo-white.svg" alt="KARAR" width="233" height="60"/>\n\t\t\t\t\t</a>\n\t\t\t\t</div>\n\t\t\t\t<div class="flex middle">\n\t\t\t\t\t<form action="/ara" method="get">\n\t\t\t\t\t\t<div class="search-wrapper flex middle">\n\t\t\t\t\t\t\t<input name="key" class="search-input" type="text" placeholder="Aranacak kelime">\n\t\t\t\t\t\t\t<i class="icon icon-search"></i>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</form>\n\t\t\t\t\t<div class="weather flex middle">\n\t\t\t\t\t\t<i class="icon icon-accu-12"></i>\n\t\t\t\t\t\t<span class="value">7\xc2\xb0</span>\n\t\t\t\t\t\t<div class="parameter  margin-left-md">\n\t\t\t\t\t\t\t<div class="city">\xc4\xb0stanbul</div>\n\t\t\t\t\t\t\t<div>Hafif ya\xc4\x9fmur</div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t\t<div class="main-nav">\n\t\t\t<div class="container">\n\t\t\t\t<ul class="flex middle">\n\t\t\t\t\t<li>\n\t\t\t\t\t\t<a href="/" alt="Anasayfa"><i class="icon-home"></i> </a>\n\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/guncel-haberler" alt="G\xc3\xbcncel">G\xc3\xbcncel</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/yazarlar" alt="Yazarlar">Yazarlar</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/dunya-haberleri" alt="D\xc3\xbcnya">D\xc3\xbcnya</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/ekonomi-haberleri" alt="Ekonomi">Ekonomi</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/spor-haberleri" alt="Spor">Spor</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/hayat-haberleri" alt="Hayat">Hayat</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/karar-tv" alt="Karar Tv">Karar Tv</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/foto-galeri" alt="Foto Galeri">Foto Galeri</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/gorusler" alt="G\xc3\xb6r\xc3\xbc\xc5\x9fler">G\xc3\xb6r\xc3\xbc\xc5\x9fler</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t<a href="/resmi-ilanlar" alt="Resmi \xc4\xb0lanlar">Resmi \xc4\xb0lanlar</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t<a class="menu show-all-menu" aria-label="Menu" href="#"><i class="icon-menu"></i></a>\n\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t</div>\n\t\t</div>\n\t</header>\n\t<div class="last-news">\n\t\t<div class="container flex middle">\n\t\t\t<div class="block-title"><a href="/son-dakika">SON DAK\xc4\xb0KA :</a>\n\t\t\t</div>\n\t\t\t<div class="news-content">\n\t\t\t\t<div class="swiper-container">\n\t\t\t\t\t<div class="swiper-wrapper">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/bahceliden-ozlem-gursese-dayanisma-telefonu-butun-gazeteciler-icin-1925405">Bah\xc3\xa7eli\'den \xc3\x96zlem G\xc3\xbcrses\'e dayan\xc4\xb1\xc5\x9fma telefonu: \'B\xc3\xbct\xc3\xbcn gazeteciler i\xc3\xa7in g\xc3\xbczel bir \xc5\x9fey yapt\xc4\xb1\'</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/yalcin-akdogan-devlet-beyin-konusmasini-duyunca-elimdeki-catali-dusurdum-1925400">Yal\xc3\xa7\xc4\xb1n Akdo\xc4\x9fan: Devlet Bey\'in konu\xc5\x9fmas\xc4\xb1n\xc4\xb1 duyunca elimdeki \xc3\xa7atal\xc4\xb1 d\xc3\xbc\xc5\x9f\xc3\xbcrd\xc3\xbcm</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/unlu-meteorolog-uyardi-kar-kapida-soguklar-artiyor-iste-sehir-sehir-1925397">\xc3\x9cnl\xc3\xbc meteorolog uyard\xc4\xb1: Kar kap\xc4\xb1da, so\xc4\x9fuklar art\xc4\xb1yor! \xc4\xb0\xc5\x9fte \xc5\x9fehir \xc5\x9fehir hava durumu!</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/anne-ve-babalar-bugun-sok-markete-akin-ediyor-bebek-bezinden-battaniye-1925396">Anne ve babalar bug\xc3\xbcn \xc5\x9eok markete ak\xc4\xb1n ediyor! Bebek bezinden battaniye yorgana kadar... \xc5\x9eok 15 Ocak 2025 katalo\xc4\x9fu</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/son-dakika-istanbulda-toplu-ulasima-yuzde-35-zam-1925392">\xc4\xb0stanbul\'da toplu ula\xc5\x9f\xc4\xb1ma y\xc3\xbczde 35 zam</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/yeni-yol-partisinin-ilk-grup-toplantisi-davutoglu-konusuyor-canli-1925386">Yeni Yol Partisi\'nin ilk grup toplant\xc4\xb1s\xc4\xb1nda Davuto\xc4\x9flu s\xc3\xb6z ald\xc4\xb1: \xc4\xb0ktidar ve ana muhalefete meydan okuduk</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/meb-ekys-basvurulari-basladi-iste-basvuru-tarihleri-sinav-ucreti-ve-1925383">MEB-EKYS ba\xc5\x9fvurular\xc4\xb1 ba\xc5\x9flad\xc4\xb1! \xc4\xb0\xc5\x9fte ba\xc5\x9fvuru tarihleri, s\xc4\xb1nav \xc3\xbccreti ve s\xc4\xb1nav tarihi!</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/tuik-ucretli-calisan-sayisi-2024-kasim-ayinda-yuzde-29-artti-1925384">T\xc3\x9c\xc4\xb0K: \xc3\x9ccretli \xc3\xa7al\xc4\xb1\xc5\x9fan say\xc4\xb1s\xc4\xb1 2024 Kas\xc4\xb1m ay\xc4\xb1nda y\xc3\xbczde 2,9 artt\xc4\xb1</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/sonunda-bunu-da-yaptilar-tarim-yapmak-artik-cok-kolay-agac-budama-1925379">Sonunda bunu da yapt\xc4\xb1lar! Tar\xc4\xb1m yapmak art\xc4\xb1k \xc3\xa7ok kolay: A\xc4\x9fa\xc3\xa7 budama derdine son veren teknoloji</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="swiper-slide flex middle">\n\t\t\t\t\t\t\t\t<a class="news-title" href="/guncel-haberler/fidan-kuzey-makedonya-avrupa-isleri-bakani-murtezani-ile-gorustu-1925378">Fidan, Kuzey Makedonya Avrupa \xc4\xb0\xc5\x9fleri Bakan\xc4\xb1 Murtezani ile g\xc3\xb6r\xc3\xbc\xc5\x9ft\xc3\xbc</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n<section class="breadcrumbs">\n\t<div class="container">\n\n\t\t<ol>\n\t\t\t<li><a href="https://www.karar.com/"><span><i class="icon-home"></i> Anasayfa</span></a></li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href="https://www.karar.com/yazarlar"><span>Yazarlar</span></a></li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href="https://www.karar.com/yazarlar/zafer-acar"><span>Zafer Acar</span></a></li>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><span>Herkes nerede?</span></li>\n\t\t\t\t\t\t\t\t\t</ol>\n\n\t</div>\n</section>\t<main role="main">\r\n\t\t<div class="banner-pageskin container"><div class="pageskin-left"><div class=" fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_L" data-sizes="[[160, 600], [120, 240], [120, 600]]" data-device="desktop"></the-ads></div></div><div class="pageskin-right"><div class=" fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_R" data-sizes="[[160, 600], [120, 240], [120, 600]]" data-device="desktop"></the-ads></div></div></div>\t\t<div class="container section-padding-gutter">\r\n\t\t\t\t\t\t<section class="banner banner-wide"><the-ads data-adunit="/karar.com/karar_desktop_masthead" data-sizes="[[728, 90], [970, 250], [970, 90], [1000, 250], \'fluid\']" data-device="desktop"></the-ads></section>\n\t\t\t\t\t<div class="page-content author-page">\r\n\r\n\t<div class="author-info box-shadow">\n\t<header class="w-100">\n\t\t<a href="/yazarlar">Bug\xc3\xbcnk\xc3\xbc Yazarlar</a>\n\t\t<a href="/yazarlar#tumu">T\xc3\xbcm Yazarlar</a>\n\t</header>\n\t<div class="image r1x1">\n\t\t<img src="https://cdn.karar.com/author/75_b.jpg" alt="Zafer Acar"/>\n\t</div>\n\t<div class="info">\n\t\t<h1 class="name">Zafer Acar</h1>\n\t\t\t\t\t<div class="mb-2"><span data-erot="mnsrenpne@xnene.pbz"></span></div>\n\t\t\t\t\t\t\t<a class="other" href="/yazarlar/zafer-acar" rel="author"><span>Yazar\xc4\xb1n T\xc3\xbcm Yaz\xc4\xb1lar\xc4\xb1 &gt;</span></a>\n\t\t\t</div>\n\t<div class="author-social social">\n\t\t\t\t\t<a href="https://www.facebook.com/KararHaber " target="_blank" rel="nofollow noopener"><i class="icon-facebook"></i></a>\n\t\t\t\t\t\t\t<a href="https://twitter.com/zaferNasa" target="_blank" rel="nofollow noopener"><i class="icon-twitter"></i></a>\n\t\t\t\t\t\t\t<a href="https://www.instagram.com/kararhaber" target="_blank" rel="nofollow noopener"><i class="icon-instagramm"></i></a>\n\t

In [50]:
soup=BeautifulSoup(page.content,"html.parser")

In [52]:
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="tr">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Herkes nerede? - Zafer Acar</title>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." name="description"/>
<link href="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" rel="canonical"/>
<link href="https://www.karar.com/amp/yazarlar/zafer-acar/herkes-nerede-7320" rel="amphtml"/>
<meta content="article" property="og:type"/>
<meta content="KARAR" property="og:site_name"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" property="og:url"/>
<meta content="Herkes nerede? - Zafer Acar" property="og:title"/>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." property="og:description"/>
<meta content="https://cdn.karar.com/author/zafer-acar-002.jpg" property="og:image"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@KararHaber" name="twitter:site"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" name="twitter:url"/>
<meta content="Herkes nerede? - Zafer Acar" name="twitter:title"/>
<meta content="Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine..." name="twitter:description"/>
<meta content="https://cdn.karar.com/author/zafer-acar-002.jpg" name="twitter:image"/>
<meta content="Zafer Acar" name="author"/>
<meta content="Herkes nerede?" name="title"/>
<meta content="https://www.karar.com/yazarlar/zafer-acar/herkes-nerede-7320" name="url"/>
<meta content="2018-06-24T23:23:46+03:00" name="datePublished"/>
<meta content="columnist" name="articleSection"/>
<meta content="Zafer Acar" name="articleAuthor"/>
<meta content="app-id=1009271502" name="apple-itunes-app"/>
<meta content="app-id=com.labdroids.karar" name="google-play-app"/>
<meta content="668763830688221" property="fb:app_id"/>
<link href="https://www.karar.com/service/rss.php" rel="alternate" type="application/rss+xml"/>
<meta content="max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/>
<link href="/manifest.json" rel="manifest"/>
<link href="https://www.karar.com/d/assets/favicon/favicon.ico" rel="icon"/>
<meta content="CM News 6.0" name="generator"/>
<link href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://www.google-analytics.com" rel="preconnect"/>
<link href="https://tpc.googlesyndication.com" rel="preconnect"/>
<link href="https://pagead2.googlesyndication.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://www.karar.com/d/assets/bundle/karar-desktop-main.css?1727709274" rel="stylesheet"/>
<script>
			const BURL = "https://www.karar.com/",
				DURL = "https://cdn.karar.com/";
		</script>
<link href="https://cdn.karar.com/assets/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link color="#e30613" href="https://cdn.karar.com/assets/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#e30613" name="msapplication-TileColor"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="fd13614ab1" name="Petal-Search-site-verification">
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1L3TVQZ3LV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1L3TVQZ3LV');
</script>
<script>!function(){var t=document.createElement("script");t.setAttribute("src",'https://cdn.p.analitik.bik.gov.tr/tracker'+(typeof Intl!=="undefined"?(typeof (Intl||"").PluralRules!=="undefined"?'1':typeof Promise!=="undefined"?'2':typeof MutationObserver!=='undefined'?'3':'4'):'4')+'.js'),t.setAttribute("data-website-id","d9b8fdca-5069-4cc2-b3f3-6ab32564a106"),t.setAttribute("data-host-url",'//d9b8fdca-5069-4cc2-b3f3-6ab32564a106.collector.p.analitik.bik.gov.tr'),document.head.appendChild(t)}();</script>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977"></script>
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script async="" src="https://adsby.io/headerbidding/adshb.karar.prebid.js"></script>
<script>
    window.googletag = window.googletag || { cmd: [] };
    googletag.cmd.push(function () {
        googletag.pubads().disableInitialLoad();
    });

	googletag.cmd.push(function ()
	{
		mappingFull = googletag.sizeMapping().
		addSize([1024, 360], [[970, 90], [1000, 250], [970, 250]]).
		addSize([768, 360], [[728, 250], [728, 90]]).
		addSize([360, 360], [[336, 280], [300, 250]]).
		addSize([0, 0], [[320, 100],[300, 100]]).
		build();

		mappingMiddle = googletag.sizeMapping().
		addSize([768, 360], [[670, 250], [640, 300], [336, 280], [300, 250], 'fluid']).
		addSize([360, 360], [[336, 280], [300, 250]]).
		addSize([0, 0], [300, 250]).
		build();

		mappingSide = googletag.sizeMapping().
		addSize([360, 360], [[336, 280], [300, 250], 'fluid']).
		addSize([0, 0], [300, 250]).
		build();

		mappingSticky = googletag.sizeMapping().
		addSize([1024, 360], [970, 90]).
		addSize([768, 360], [728, 90]).
		addSize([0, 0], [[300, 100],[320,100]]).
		build();

		mappingPageSkin = googletag.sizeMapping().
		addSize([1720, 600], [[300, 600],[160, 600],[120, 600]]).
		addSize([1520, 600], [[160, 600],[120, 600]]).
		addSize([1440, 600], [[160, 600],[120, 600]]).
		addSize([1366, 600], [[120, 600]]).
		addSize([0, 0], []).
		build();

		mappingMobilM = googletag.sizeMapping().
		addSize([0, 0], [[300, 50], [320, 100], [320, 50], [300, 100]]).
		build();
		mappingMobilSC = googletag.sizeMapping().
		addSize([0, 0], [[300,250], [336, 280]]).
		build();


		googletag.enableServices();
	});
</script>
<script src="https://adsby.io/karar/karar.gpt.js?ver=1.15"></script>
<script src="https://adsby.io/theadsiobanner.js?ver=1.15"></script>
<!--
<script async="async" src="https://cdn.membrana.media/krr/ym.js"></script>

<script>

	window.yieldMasterCmd = window.yieldMasterCmd || [];
	window.yieldMasterCmd.push(function ()
	{
		window.yieldMaster.init({
			pageVersionAutodetect: true
		});
	});

</script>

-->
<!--script>
  window.teads_analytics = window.teads_analytics || {};
  window.teads_analytics.analytics_tag_id = "PUB_28922";
  window.teads_analytics.share = window.teads_analytics.share || function() {
    ;(window.teads_analytics.shared_data = window.teads_analytics.shared_data || []).push(arguments)
  };
</script>
<script async src="https://a.teads.tv/analytics/tag.js"></script-->
<script async="" src="https://jsc.idealmedia.io/site/839414.js"></script>
<!-- head end -->
<style>
    .article-detail .google-auto-placed{
        margin-bottom: 30px;
    }
</style> </meta></head>
<body class="body-main cat-author author-article-detail author">
<header class="main-header">
<div class="top">
<div class="container">
<div class="date">15 Ocak 2025 Çarşamba</div>
<div class="currency">
<div class="item up">
<span class="text">Altın</span>
<i class="icon icon-up-dir"></i>
<span class="value">3061.148</span>
<span class="rate">%0.37</span>
</div>
<div class="item down">
<span class="text">BIST</span>
<i class="icon icon-down-dir"></i>
<span class="value">9697.22</span>
<span class="rate">%0,19</span>
</div>
<div class="item up">
<span class="text">Dolar</span>
<i class="icon icon-up-dir"></i>
<span class="value">35.4871</span>
<span class="rate">%0.01</span>
</div>
<div class="item down">
<span class="text">Euro</span>
<i class="icon icon-down-dir"></i>
<span class="value">36.5747</span>
<span class="rate">%0.10</span>
</div>
</div>
<div class="social">
<a class="youtube" href="https://www.youtube.com/channel/UCoLyFzOzAzNG_-oR-O4relg?sub_confirmation=1" rel="nofollow noopener noreferrer" target="_blank" title="Youtube ile takip et"><i class="icon icon-youtube-play"></i></a>
<a class="instagram" href="https://www.instagram.com/kararhaber" rel="nofollow noopener noreferrer" target="_blank" title="İnstagram ile takip et"><i class="icon icon-instagramm"></i></a>
<a class="facebook" href="https://www.facebook.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Facebook ile takip et"><i class="icon icon-facebook"></i></a>
<a class="twitter" href="https://twitter.com/KararHaber" rel="nofollow noopener noreferrer" target="_blank" title="Twitter ile takip et"><i class="icon icon-twitter"></i></a>
</div>
</div>
</div>
<div class="center">
<div class="container">
<div class="logo relative">
<a href="https://www.karar.com/" rel="home" title="KARAR">
<img alt="KARAR" class="lazy" data-src="https://www.karar.com/d/assets/logo-white.svg" height="60" loading="lazy" width="233"/>
</a>
</div>
<div class="flex middle">
<form action="/ara" method="get">
<div class="search-wrapper flex middle">
<input class="search-input" name="key" placeholder="Aranacak kelime" type="text"/>
<i class="icon icon-search"></i>
</div>
</form>
<div class="weather flex middle">
<i class="icon icon-accu-12"></i>
<span class="value">7°</span>
<div class="parameter margin-left-md">
<div class="city">İstanbul</div>
<div>Hafif yağmur</div>
</div>
</div>
</div>
</div>
</div>
<div class="main-nav">
<div class="container">
<ul class="flex middle">
<li>
<a alt="Anasayfa" href="/"><i class="icon-home"></i> </a>
</li>
<li>
<a alt="Güncel" href="/guncel-haberler">Güncel</a>
</li>
<li>
<a alt="Yazarlar" href="/yazarlar">Yazarlar</a>
</li>
<li>
<a alt="Dünya" href="/dunya-haberleri">Dünya</a>
</li>
<li>
<a alt="Ekonomi" href="/ekonomi-haberleri">Ekonomi</a>
</li>
<li>
<a alt="Spor" href="/spor-haberleri">Spor</a>
</li>
<li>
<a alt="Hayat" href="/hayat-haberleri">Hayat</a>
</li>
<li>
<a alt="Karar Tv" href="/karar-tv">Karar Tv</a>
</li>
<li>
<a alt="Foto Galeri" href="/foto-galeri">Foto Galeri</a>
</li>
<li>
<a alt="Görüşler" href="/gorusler">Görüşler</a>
</li>
<li>
<a alt="Resmi İlanlar" href="/resmi-ilanlar">Resmi İlanlar</a>
</li>
<li>
<a aria-label="Menu" class="menu show-all-menu" href="#"><i class="icon-menu"></i></a>
</li>
</ul>
</div>
</div>
</header>
<div class="last-news">
<div class="container flex middle">
<div class="block-title"><a href="/son-dakika">SON DAKİKA :</a>
</div>
<div class="news-content">
<div class="swiper-container">
<div class="swiper-wrapper">
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/bahceliden-ozlem-gursese-dayanisma-telefonu-butun-gazeteciler-icin-1925405">Bahçeli'den Özlem Gürses'e dayanışma telefonu: 'Bütün gazeteciler için güzel bir şey yaptı'</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/yalcin-akdogan-devlet-beyin-konusmasini-duyunca-elimdeki-catali-dusurdum-1925400">Yalçın Akdoğan: Devlet Bey'in konuşmasını duyunca elimdeki çatalı düşürdüm</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/unlu-meteorolog-uyardi-kar-kapida-soguklar-artiyor-iste-sehir-sehir-1925397">Ünlü meteorolog uyardı: Kar kapıda, soğuklar artıyor! İşte şehir şehir hava durumu!</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/anne-ve-babalar-bugun-sok-markete-akin-ediyor-bebek-bezinden-battaniye-1925396">Anne ve babalar bugün Şok markete akın ediyor! Bebek bezinden battaniye yorgana kadar... Şok 15 Ocak 2025 kataloğu</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/son-dakika-istanbulda-toplu-ulasima-yuzde-35-zam-1925392">İstanbul'da toplu ulaşıma yüzde 35 zam</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/yeni-yol-partisinin-ilk-grup-toplantisi-davutoglu-konusuyor-canli-1925386">Yeni Yol Partisi'nin ilk grup toplantısında Davutoğlu söz aldı: İktidar ve ana muhalefete meydan okuduk</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/meb-ekys-basvurulari-basladi-iste-basvuru-tarihleri-sinav-ucreti-ve-1925383">MEB-EKYS başvuruları başladı! İşte başvuru tarihleri, sınav ücreti ve sınav tarihi!</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/tuik-ucretli-calisan-sayisi-2024-kasim-ayinda-yuzde-29-artti-1925384">TÜİK: Ücretli çalışan sayısı 2024 Kasım ayında yüzde 2,9 arttı</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/sonunda-bunu-da-yaptilar-tarim-yapmak-artik-cok-kolay-agac-budama-1925379">Sonunda bunu da yaptılar! Tarım yapmak artık çok kolay: Ağaç budama derdine son veren teknoloji</a>
</div>
<div class="swiper-slide flex middle">
<a class="news-title" href="/guncel-haberler/fidan-kuzey-makedonya-avrupa-isleri-bakani-murtezani-ile-gorustu-1925378">Fidan, Kuzey Makedonya Avrupa İşleri Bakanı Murtezani ile görüştü</a>
</div>
</div>
</div>
</div>
</div>
</div>
<section class="breadcrumbs">
<div class="container">
<ol>
<li><a href="https://www.karar.com/"><span><i class="icon-home"></i> Anasayfa</span></a></li>
<li><a href="https://www.karar.com/yazarlar"><span>Yazarlar</span></a></li>
<li><a href="https://www.karar.com/yazarlar/zafer-acar"><span>Zafer Acar</span></a></li>
<li><span>Herkes nerede?</span></li>
</ol>
</div>
</section> <main role="main">
<div class="banner-pageskin container"><div class="pageskin-left"><div class="fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_L" data-device="desktop" data-sizes="[[160, 600], [120, 240], [120, 600]]"></the-ads></div></div><div class="pageskin-right"><div class="fixed"><the-ads data-adunit="/karar.com/karar_desktop_pageskin_R" data-device="desktop" data-sizes="[[160, 600], [120, 240], [120, 600]]"></the-ads></div></div></div> <div class="container section-padding-gutter">
<section class="banner banner-wide"><the-ads data-adunit="/karar.com/karar_desktop_masthead" data-device="desktop" data-sizes="[[728, 90], [970, 250], [970, 90], [1000, 250], 'fluid']"></the-ads></section>
<div class="page-content author-page">
<div class="author-info box-shadow">
<header class="w-100">
<a href="/yazarlar">Bugünkü Yazarlar</a>
<a href="/yazarlar#tumu">Tüm Yazarlar</a>
</header>
<div class="image r1x1">
<img alt="Zafer Acar" src="https://cdn.karar.com/author/75_b.jpg"/>
</div>
<div class="info">
<h1 class="name">Zafer Acar</h1>
<div class="mb-2"><span data-erot="mnsrenpne@xnene.pbz"></span></div>
<a class="other" href="/yazarlar/zafer-acar" rel="author"><span>Yazarın Tüm Yazıları &gt;</span></a>
</div>
<div class="author-social social">
<a href="https://www.facebook.com/KararHaber " rel="nofollow noopener" target="_blank"><i class="icon-facebook"></i></a>
<a href="https://twitter.com/zaferNasa" rel="nofollow noopener" target="_blank"><i class="icon-twitter"></i></a>
<a href="https://www.instagram.com/kararhaber" rel="nofollow noopener" target="_blank"><i class="icon-instagramm"></i></a>
</div>
</div>
<script>
	document.addEventListener("cmready", function()
	{
		$('[data-erot]').each(function()
		{
			let elm = $(this);
			$(this).replaceWith('<a href="mailto:' + elm.attr('data-erot').replace(/[a-zA-Z]/g, function(c)
			{
				return String.fromCharCode((c <= "Z" ? 90 : 122) >= (c = c.charCodeAt(0) + 13) ? c : c - 26);
			}) + '"><i class="icon-mail"></i></a>')
		})
	});
</script> <div class="row">
<div class="col-8">
<div class="article-detail author-article-detail">
<div class="content-date">
<time datetime="2018-06-24 23:23:46">24/06/2018 23:23</time>
</div>
<div class="content-heading">
<h1 class="content-title">Herkes nerede?</h1>
</div>
<div class="content-tools flex center between mb-4">
<div class="bookmark-block" data-type="99"></div>
<div class="flex">
<div class="text-size mr-4">
<span class="icon-plus" onclick="changeTextSize('.article-content .text-content', 'u');" role="button" title="Yazıyı büyüt"></span>
<span class="icon-fontsize"></span>
<span class="icon-minus" onclick="changeTextSize('.article-content .text-content', 'd');" role="button" title="Yazıyı küçült"></span>
</div>
<div class="share-block-99">
<span class="icon-print" onclick="window.print();" role="button" title="Yazdır"></span>
<span class="icon-comment-2 comment" onclick="$.scrollTo('#comment_form_7320', 600);" role="button" title="Yorum Yap">
<sup>2</sup>
</span>
</div>
</div>
</div>
<article class="article-content">
<div class="text-content">
<p class="p1"><span class="s1">Los Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine en yakın şehir ise 56 km uzaklıktaki Santa Fe. Los Alamos’ta hayatını devam ettirenler alışveriş ve eğlence için Santa Fe’ye gidip geliyorlar. Yıllar önce yolum Santa Fe’ye düşmüştü. Hazır buraya kadar gelmişken şu Los Alamos’u bir ziyaret edelim dedik. Fakat Santa Fe ziyaretim kızılderililerin yaz festivaline denk gelmişti ve otellerde yer yoktu. Geceyi Santa Fe’nin güneyindeki Albuquerque şehrinde geçirince Los Alamos’a gitmek kısmet olmadı.</span></p><p class="p2"><span class="s1">Peki Los Alamos kasabası bize neyi hatırlatıyor? Tabiki Atom bombasını. İlk atom bombasının yapımı ve test edilmesi ve II. Dünya Savaşı’nın bilimle sonlandırılması tam da bu kasabada bulunan Los Alamos Ulusal Laboratuvar’ında planlanıyor. Hal böyle olunca bu minik kasaba 1940’lardan günümüze kadar hep bilim insanlarını misafir etmiş ve uzun yıllar çoğu Nobel Ödülü sahibi binlerce bilim insanı burada yaşamışlar.</span></p><div class="banner banner-wide"><the-ads data-adunit="/karar.com/karar_desktop_inarticle_middle1" data-device="desktop" data-sizes="[[480, 320], [300, 250], [250, 250], [500, 250], [336, 280], 'fluid']"></the-ads>
<!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5668552793696977"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block; text-align:center;"
     data-ad-layout="in-article"
     data-ad-format="fluid"
     data-ad-client="ca-pub-5668552793696977"
     data-ad-slot="6380903800"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});

In [56]:
soup.select("h1.content-title")[0].text

'Herkes nerede?'

In [58]:
soup.select("article.article-content")[0].text

'\n\nLos Alamos Amerika’nın New Mexico eyaletinin 2300 metre rakımlı, bir adet süpermarketi ve 2 kafesi olan 12 bin nüfuslu minik bir kasabası. Kendisine en yakın şehir ise 56 km uzaklıktaki Santa Fe. Los Alamos’ta hayatını devam ettirenler alışveriş ve eğlence için Santa Fe’ye gidip geliyorlar. Yıllar önce yolum Santa Fe’ye düşmüştü. Hazır buraya kadar gelmişken şu Los Alamos’u bir ziyaret edelim dedik. Fakat Santa Fe ziyaretim kızılderililerin yaz festivaline denk gelmişti ve otellerde yer yoktu. Geceyi Santa Fe’nin güneyindeki Albuquerque şehrinde geçirince Los Alamos’a gitmek kısmet olmadı.Peki Los Alamos kasabası bize neyi hatırlatıyor? Tabiki Atom bombasını. İlk atom bombasının yapımı ve test edilmesi ve II. Dünya Savaşı’nın bilimle sonlandırılması tam da bu kasabada bulunan Los Alamos Ulusal Laboratuvar’ında planlanıyor. Hal böyle olunca bu minik kasaba 1940’lardan günümüze kadar hep bilim insanlarını misafir etmiş ve uzun yıllar çoğu Nobel Ödülü sahibi binlerce bilim insanı burada yaşamışlar.\n***Los Alamos’ta yaşayan bu bilim insanlarının en önemlilerinden birisi de İtalyan bilim adamı Enrico Fermi idi. Enrico Fermi 1901 yılında Roma’da doğdu. Annesi ilkokul öğretmeni, babası ise demiryolları bakanlığında çalışıyordu. Atom bombasının babası olarak bilinen Fermi fizik eğitimi aldıktan sonra indüklenmiş radyoaktivite çalışmaları ile 1938 yılında Nobel Fizik Ödülü’nü kazandı. Stokholm’de Nobel Ödülü’nü alır almaz soluğu New York’ta aldı ve İtalya’ya bir daha dönmedi.***Enrico Fermi Şikago’da ilk nükleer reaktörü faaliyete geçirdi. Sonra da Manhattan Projesi’ne dahil oldu ve Los Alamos Ulusal Laboratuvarı’nda çalışmaya başladı. Atom bombasının yapımı ve Japonya’da patlatılmasıyla son bulan II. Dünya Savaşı’ndan sonra da Los Alamos Ulusal Laboratuvarı bilimde ve teknolojide yerini korudu. Bugün Los Alamos, dünyanın en büyük bilim ve teknoloji kurumlarından biridir. Ulusal güvenlik, uzay araştırmaları, nükleer füzyon, yenilenebilir enerji, tıp, nanoteknoloji ve süper bilgisayarlar gibi alanlarda çok disiplinli araştırmalar yürütmektedir.1950 yılında Enrico Fermi bilim insanı arkadaşlarıyla Los Alamos’ta öğle yemeğinde o sıralarda görülen bir UFO olayı tartışılırken şu soruyu sordu: “Herkes nerede?”. Burda herkesten kasıt dünya dışı akıllı canlılardı. İşte bu sorudan sonra uzaylılar mevzu bahis olunca bilim dilinde Fermi Paradoksu en önemli argümanlardan birisi oldu.Dünya dışı akıllı canlılar için bugün iki büyük fikir var. Bunlardan biri, galaksimizdeki uygarlıkların sayısını tahmin edebilen Drake Denklemi’dir. Diğeri ise, eğer burada herhangi bir yerde var olsaydı, zeki uzaylıları görmemiz gerektiğini iddia eden Fermi paradoksu.Galaksimizde 200 milyardan fazla yıldız var. Bunların içerisinden etrafında gezegen olan yıldızlar hesaba katıldığında tahmini gezegen sayısı yıldız sayısının birkaç katıdır. Bu durumda dünya dışı zeki hayatında ortaya çıkma ihtimalini çok düşük tuttuğumuzda bile yine de galaksimiz Samanyolu’nda çok sayıda uzaylı olmak zorundadır. Öte yandan Kepler Uzay Teleskobu’nun katkılarıyla 4 bine yakın öte gezegen keşfedilmiştir: Bu verileri inceleyen bilim insanları hayat olabilecek muhtemel gezegen sayısının 17 milyar civarında olabileceğini hesap etmektedirler.***Madem bu kadar uygarlık var, Enrico Fermi’nin sorusu şu: Öyleyse neredeler ve neden şimdiye kadar bir delil bulamadık?Bu soruya elliden fazla cevap verilmiş. Yıldızlar birbirlerine çok uzaklar iletişim kurmak çok zor ve zaman alır. Uzaylılar teknoloji olarak çok gelişmiş ve bizim içimizdeki savaşları, kavgaları görüp bizden uzak durmaya çalışıyor olabilirler. Beyin yapıları bizden birkaç basamak üstün olabilir. Mesela insanlar bir iş yapacakları zaman solucanlardan fikir danışmadıkları gibi, uzaylılar da bizi alt beyin olarak görüp bizimle iletişim kurmuyor olabilirler. Veya onlar bize sinyaller göndermişler fakat bizim teknolojimiz henüz algılayamıyor. Veya biz Matrix ve Truman Show gibi bilgisayar yazılımının içindeki figürleriz. Ya da bu kâinatta yalnınız ve kimsemiz yok, fakat biz birbirimizi öldürüp duruyoruz.Trump’ın uzay ordusuGeçen hafta ABD başkanı Trump Amerikan ordusunun 6. Kolu olarak Uzay Kuvvetleri’ni kurma talimatını verdi. Uzayda yaşayan çoğu Amerikalı üç-beş astronottan başka kimse şimdilik yok. Fakat uzay çalışmaları hızlı gelişiyor. Yakın zamanda çok sayıda yolcu uzay otellerine, Ay’a ve Mars’a gidecek. Peki bu kadar çok kişiyi kim uzaya götürecek?Los Angeles Belediye Başkanı Eric Garcetti SpaceX’e Los Angeles Limanı’nda Mars Mekiği yapma izni verdi. Mars Mekiği tam 100 kişiyi ve 150 ton kargoyu uzaya götürecek şekilde tasarlandı. Başkan Garcetti “Bu yıl bize birşey öğrettiyse o da büyük düşünmek ve ulaşılamayacak hayallerin peşinden gitmektir” dedi. Mars mekiği tam 16 katlı ve 19 katlı roket tarafından fırlatılacak ve yakıt olarak diğer gezegenlerde de kolayca elde edilebilen sıvı metan gazı kullanacak.Hal böyle olunca bir seferde 100 kişi uzaya gidebilecek. Tabiki bu insanlardan vergi toplayıp, asayişi sağlamak ve en önemlisi onlara demokrasi götürmek için güçlü bir orduya ihtiyaç olacak. Biz seçimlerle uğraşırken ABD uzaya ordu göndermek için kolları sıvamış durumda. ‘’Uzayda Amerikan hakimiyetine sahip olmak zorundayız’’ diyen Trump, uzay araştırmaları yapmak, uzay mekiği üretmek ve yeni roketler tasarlamak için öncülük etmek zorunda olduklarını belirtti. Vietnam’a, Afganistan’a, Irak’a ve diğer üçüncü Dünya ülkelerine demokrasi götüren ABD ordusu bakalım uzaya nasıl bir demokrasi getirecek? \n'

In [62]:
page=requests.get("https://www.karar.com/yazarlar/zafer-acar")

In [64]:
soup=BeautifulSoup(page.content,"html.parser")

In [72]:
linkler=soup.find_all("article",{"class":"item box-shadow"})

In [74]:
yazilar = []
basliklar = []
for i in range(4):
    page=requests.get("https://www.karar.com/yazarlar/zafer-acar?page="+str(i+1))
    soup = BeautifulSoup(page.content, "html.parser")
    linkler = soup.find_all("article", {"class":"item box-shadow"})
    for link in linkler:
        link1= "https://www.karar.com"+link.a.get("href")
        baslik = link.h3.text
        page2=requests.get(link1)
        soup2 = BeautifulSoup(page2.content, "html.parser")
        makale=soup2.select("article.article-content")[0].text
        yazilar.append(makale)
        basliklar.append(baslik)

In [75]:
import pandas as pd

In [78]:
df=pd.DataFrame(columns=["Title","Article"])

In [80]:
df["Title"]=basliklar
df["Article"]=yazilar

In [82]:
df.head()

,Title,Article
0,Engellilerin umudu yapay zeka,\n\nYapay zeka her alanda büyük değişimler ve ...
1,Kuantum yapay zeka,\n\nTeknolojik gelişmeler baş döndürücü hızla ...
2,Astronot 001,\n\nUzay çalışmaları ve uçuşları küçüklüğümden...
3,Çin’in uzay programı tam gaz,\n\nUzay çalışmalarında ne kadar ileride iseni...
4,Yapay zeka ile çip tasarımı,"\n\nGeçtiğimiz hafta Google, bilgisayar çipler..."

In [84]:
df["Article"]=df["Article"].str.replace("\n","")

In [86]:
df["Article"][0]

'Yapay zeka her alanda büyük değişimler ve gelişimler vaad ediyor. Almanya’da yapılan yeni bir araştırma, görme engelli vatandaşlarımızın gerçek dünyada gezinmelerine yardımcı olmak için GPU ile çalışan, taşınabilir bir sistem geliştirdi. Daha önce de yapay zeka ile görme engelli vatandaşlarımızın belirlenen ve işaretlenen yollarda rahatça koşmaları sağlanmıştı. Bu kez sırtınızda taşıyacağınız bir laptop ve gözlüğünüze monte edebileceğiniz bir kamera ile normal insan gibi gezmek, görmek, karşıdan gelen arkadaşlarınızı tanımak ve selam vermek artık problem olmaktan çıkacak.Ülkemizde maalesef fiziksel ve zihinsel özürlü çok sayıda vatandaşımız var. Bunların en zoru muhtemelen görme ve işitme. Tekerlekli sandalyeye mahkum olan veya bir tekerlekli sandalye bile bulamayan çok sayıda engelli vatandaşımız da var. Devletimiz engelli vatandaşlarımıza bir miktar sahip çıksa da, özürlü bir bireye sahip olan aileler, bu meseleyi sanki utanç verici bir şeymiş gibi düşünüyor ve çocuklarını topluma çıkarmama veya bir odaya kapatıp hayatını orada geçirmesini istiyor. Ayrıca engelli vatandaşlarımız bir başkasının yardımı ve desteği olmadan dışarı bile çıkamıyor ve hep bir başkasına bağımlı yaşıyor. Hatta bazen yatalak babasına bakmak için hiç evlenmeyen, babası vefat edince bir işe girmediği için zor durumda kalan kızların hikayelerini duyuyoruz. Tam bu noktada yapay zeka devreye giriyor ve görmeyen gözlere görme, duymayan kulaklara işitme olayını çözmüş gibi görünüyor.Yapay zekanın en önemli iki alanı olan Bilgisayarlı Görme (Computer Vision) ve Doğal Dil İşleme (NLP) ile artık görme ve işitme engelli vatandaşlarımız, Coğrafi Bilgi Sistemler (Geographic Information Systems - GIS) ile de tekerlekli sandalyeye mahkum insanlarımız başkasına bağımlı yaşamaktan kurtuluyor ve normal bir birey gibi seyahat edebiliyor, koşabiliyor ve konuşabiliyorlar.Computer Vision veya Bilgisayarın gözü en büyük gelecek vaat eden yapay zeka alanlarından birisi. Yapay zeka dersi verdiğim öğrenciler, muhtemelen görselliği fazla olduğu için, en çok bu konudan etkileniyorlar ve bu konuda uzmanlaşmak istiyorlar. Çok rahatlıkla geliştirebileceğimiz bir yapay zeka modelini, gözlüğümüze monte edilebilen bir kameraya yüklediğimizde karşıdan gelen insanları yüz tanıma sistemleri ile tanıyıp Doğal Dil İşleme ile kimin yaklaşmakta olduğunu kulağınıza fısıldayabiliyor. Tam konuşma mesafesine geldiğinizde size durmanızı ve selam vermenizi söylüyor. Yine aynı yapay zeka algoritması yoldaki işaretleri okuyup anlayabiliyor. Yürüyüş alanlarında her bir nesneyi ve engeli tanıyor ve gerçek zamanlı olarak görme özürlü vatandaşlarımızı yönlendirebiliyor. Hatta makineler 2017 yılından bu yana insanlardan daha iyi görmeye başladılar. Bu sayede artık görme özürlü kişiler araba bile kullanabilir ve görmemek problem olmaktan çıkar. Ayrıca Bilgisayarlı Görme, Doğal Dil İşleme ile birleştiğinde müthiş bir takım arkadaşı oluyorlar. Çünkü makine gördüğü nesneleri sese çevirmek zorunda. İşte burada doğal dil işleme devreye giriyor ve ve eğittiğimiz modeller gördüğü kişileri ve nesneleri kelimelere doğal dil işleme sayesinde döküyor. Resimler ve videolar bilgisayar için çok boyutlu matrislerden ibaret. Resimler piksellerden oluşur ve bu piksellerde RGB renk modeline göre 3 farklı renkten rakamlar vardır. Diğer bütün renkler RGB (Kırmızı  - Yeşil - Mavi) renklerinin 0’dan 255’e kadar olan değerlerinden oluşur. Bu durumda resimler bilgisayar için Lineer Cebir’de ‘Tensor’ ismini verdiğimiz çok boyutlu matrislerdir. İşte kameralar kendisine daha önce gösterilen resimlerin matrislerine benzer matris gördüklerinde nesneleri ve insanları tanıyabiliyorlar.Geçtiğimiz yıllarda yaz aylarında yaptığım bir bilimsel araştırmanın sonuçlarını Los Angeles’ta akademik bir ortamda anlatıyordum. İşitme özürlü bir öğrencimiz de izlemeye gelmişti. Üniversitemiz bu öğrenciye iki tane interpreter vermiş. Bu kişiler dönüşümlü olarak benim anlattıklarımı işaret dili ile işitme engelli öğrenciye anlatıyorlardı. Bu iki kişi, gün boyu bu öğrencinin derslerine giriyorlar ve profesörlerin derste anlattıklarını işaret diline çeviriyorlar ve bu öğrenci bu sayede üniversite okuyabiliyor. Ancak bu işitme engelli öğrenci akşam evinde veya başka alanlarda olduğunda anlatılanları duyamıyor. Arkadaşlarının söylediklerini anlamıyor. Beraber ders çalışabileceği insanlar yok. Mesela havaalanında tek başına yolculuk yapıyor. Uçağa bineceği kapı numarası son anda değişti. O zaman yapılan anonsları duymayacağı için uçağı kaçırması kuvvetle muhtemel. İşte yapay zekaya daha evvelki konuşmalar ve işaret dilindeki ifadeleri gösterilirse, sanal bir karakter ile bütün konuşmaların işaret diline çevrilmesi işten bile değil. Bu konuda da ciddi çalışmalar mevcut ve çok büyük başarılar elde edildi. Hal böyle olunca konuşulanları,duyuruları ve anonsları cep telefonu ekranında işaret diline çeviren bir uygulama ile işitme engeli artık engel olmaktan çıkıyor.Yapay zekanın başka bir parlayan yıldızı ise coğrafi bilgi sistemleridir. Bu sistem sayesinde veriler haritalar üzerine yüklenebiliyor ve veri analizi ile hangi konumda ne iş yapılırsa başarılı olur ve bir işyeri en optimum düzeyde nasıl çalışır gibi veriye dayalı kararlar verilebiliyor. Otonom araçlar, coğrafi bilgi sistemleri, bilgisayarlı görme, RADAR ve LIDAR teknolojileri ile yollarını bulabiliyorlar. Bu teknoloji ile tekerlekli sandalyeye mahkum yakınlarımız cep telefonlarına gitmek istedikleri adresi girecekler veya söyleyecekler. Yapay zeka ile donanımlı araçlar onları kimseye muhtaç olmadan gitmek istedikleri yerlere götürecekler. Akrabaları ise bu araçları hem görüntülü, hem de harita üzerinde takip edip yakınımızın güvende olup olmadığını takip edeceğiz.Gençlerimizde son zamanlarda gördüğüm şey çok vahim. Bilim insanlarına, bilim ve teknolojiye, yapay zekaya ilgi duyacaklarına, parası ve nüfuzu olan kişilere özeniyorlar, filmler ve diziler basit küfürler ve birbirinin tuzağını kuran sığ tartışmalardan ibaret.On binlerce kişi milletvekili olabilmek için varlarını yoklarını satıp aday adayı başvurusu yapıyorlar,  lakin bilim insanı olmak için aynı gayreti göremiyoruz. Dizilerde ve filmlerde uzay, bilim, teknoloji ve yapay zeka konuları sık sık işlenmeli. Yüksek teknoloji, yapay zeka, kuantum bilgisayar çağı kapıya geldi dayandı. Biz ise gereksiz siyasi tartışmalarla ömrümüzü harcıyoruz. '